### ISSUE TITLE
[Bug] vertical navbar overlays over all elements

### ISSUE THREAD

**Issue by abhijithvijayan** [abhijithvijayan/abhijithvijayan.in#21]
Prevents accessing components.

Although, a lot of fixes has been accepted and proposed, the issue still persits.

The styling seems to be messing this up.  

The people who are submitting a PR, please make sure, the navbar is shown and is fully accesible in mobile screens, and also all other components are touchable.

**Comment by abhijithvijayan** [comment]
Check #16 #19 #20 for previously raised(not fixed) fixes

**Comment by JohnTendik** [comment]
Lol, let me know if this fixes your issue

**Comment by abhijithvijayan** [comment]
@JohnTendik Thanks. It works great. Finally I can close this issue.
