### ISSUE TITLE
React Lifecycle methods migration

### ISSUE THREAD

**Issue by abhijithvijayan** [abhijithvijayan/abhijithvijayan.in#23]
![Screenshot from 2019-10-20 08-41-39](https://user-images.githubusercontent.com/34790378/67154196-94556d00-f315-11e9-826f-92474b4eea3d.png)

Fix the warnings

**Comment by mazsam** [comment]
Can i take this issue ?

**Comment by abhijithvijayan** [comment]
@mazsam Sure

**Comment by abhijithvijayan** [comment]
How is the PR coming up?

**Comment by thebishaldeb** [comment]
I want to work on it

**Comment by abhijithvijayan** [comment]
@thebishaldeb Have a take at it.

**Comment by thebishaldeb** [comment]
> @thebishaldeb Have a take at it.

Cool. Why is the hactoberfest tag removed though?

**Comment by abhijithvijayan** [comment]
Oops

**Comment by thebishaldeb** [comment]
None of the files are using the things which show warning. Maybe some files in node module are, and that is pretty useless to change cuz it'll be removed again after running npm install.

**Comment by abhijithvijayan** [comment]
Thanks for looking into it.
So I can close this issue right!
