### ISSUE TITLE
add animation delay to project cards on expansion

### ISSUE THREAD

**Issue by abhijithvijayan** [abhijithvijayan/abhijithvijayan.in#24]
The Expand button click mounts all the cards at once, without the smooth transition & delay

![Screenshot from 2019-10-20 08-47-44](https://user-images.githubusercontent.com/34790378/67154226-5442ba00-f316-11e9-8aae-3e26f4b54d80.png)

**Comment by rahuldkjain** [comment]
@abhijithvijayan I would love to work on this issue. Please assign it to me

**Comment by abhijithvijayan** [comment]
Done

**Comment by ramazord** [comment]
Omg xD i have done doing this but i forgot to ask to assign

**Comment by ramazord** [comment]
@abhijithvijayan can i make pull request to the work that i have been done or let @rahuldkjain doing this ?

![transition](https://user-images.githubusercontent.com/19430442/67155956-bfa28100-f342-11e9-9604-0695b76815ca.gif)

**Comment by rahuldkjain** [comment]
@ramazord as you are already done with this, there is no point in enhancing the same thing again. You go on making the pull request. @abhijithvijayan Please reassign this issue to @ramazord.

**Comment by ramazord** [comment]
@rahuldkjain Thank you very much, I really appreciate that a lot.

**Comment by abhijithvijayan** [comment]
Just shoot the PR when it's done. I will accept if it resolves the issue

**Comment by ramazord** [comment]
@abhijithvijayan It's already up at #25

**Comment by abhijithvijayan** [comment]
@rahuldkjain I will mention you in some other issue(if it comes up)
