### ISSUE TITLE
[Bug] Fix home section elements mounting transition delay

### ISSUE THREAD

**Issue by abhijithvijayan** [abhijithvijayan/abhijithvijayan.in#27]
wow.js doesn't actually work for the hero section components.
The transition delay still is not good enough

See gif. All the elements mount at the same time

![Peek 2019-10-20 14-50](https://user-images.githubusercontent.com/34790378/67157426-8de0e880-f349-11e9-9e90-e6d465304ea6.gif)

Please comment here before working on this issue.

**Comment by thetseffect** [comment]
Hi Abhijith. I would like to work on this issue.

**Comment by thetseffect** [comment]
This glitch does not occur in the local environment. The section loads in a sequential manner as required.
Please look into it.

**Comment by abhijithvijayan** [comment]
So then it is a production issue.
