### ISSUE TITLE
[Bug] Fix navbar animation 

### ISSUE THREAD

**Issue by abhijithvijayan** [abhijithvijayan/abhijithvijayan.in#28]
Animation is not smooth enough

Each item is to be fallen down with a slight delay

See gif 

![Peek 2019-10-20 14-57](https://user-images.githubusercontent.com/34790378/67157460-1d869700-f34a-11e9-9c1b-240acb9968ce.gif)

Please comment here before working on this issue.

**Comment by shravan-balasubramanian** [comment]
I will try this

**Comment by shravan-balasubramanian** [comment]
Is this already done ? :/

**Comment by abhijithvijayan** [comment]
@shravan-balasubramanian Not that I know of.

**Comment by abhijithvijayan** [comment]
Might be caused in the production build
