### ISSUE TITLE
add scrolling indicator to horizontal nav tabs

### ISSUE THREAD

**Issue by abhijithvijayan** [abhijithvijayan/abhijithvijayan.in#29]
Adding similar tab switch indicator used for the horizontal tabs for mobile screens

![Peek 2019-10-20 15-03](https://user-images.githubusercontent.com/34790378/67157530-0bf1bf00-f34b-11e9-96a6-0469197ca0f6.gif)

Currently, it is hidden for the small screens

![Peek 2019-10-20 15-013](https://user-images.githubusercontent.com/34790378/67157531-0bf1bf00-f34b-11e9-8f36-18f117911521.gif)

**Comment by uuykay** [comment]
I can have a go at this one

**Comment by uuykay** [comment]
![image](https://user-images.githubusercontent.com/32381131/67158868-788bae80-f389-11e9-81b2-7efc1466aadc.png)
This is the proposed change

**Comment by uuykay** [comment]
Apologies, maybe I have misinterpretted this one. Did you still want it to be horizontal, just that the click interaction scrolls the active tab to the left?

**Comment by abhijithvijayan** [comment]
@uuykay Sorry if I confused you.

I want that while scroller line on the mobilr devices as well

**Comment by uuykay** [comment]
@abhijithvijayan Ohh I see, ok so this is just to bring back the white scrolling line which indicates the active tab. If so I'll adjust my solution. It's late at the moment where I live so it will have to be tomorrow maybe around this time when I can work on it again

**Comment by abhijithvijayan** [comment]
I will just assign it to you then

**Comment by uuykay** [comment]
Hey @abhijithvijayan so I worked on this a bit tonight. You can check the current behaviour. It's not quite right but it is showing now, and it is moving horizontally, and resizing itself. However the issue is:

- Since there is a scroll, the position of the line will not move with the user scrolling
- Clicking the last option causes the line to move off the last item.

**Comment by uuykay** [comment]
With it being a scroll I dont think you want this interaction. My recommendation is to change it to being vertical in my original screenshot

**Comment by abhijithvijayan** [comment]
If I set it to vertical tabs, and if I keep on adding tabs more than 4, the list is gonna expand on smaller devices, and that might not be good for UX.

I will review your PR and let me look on to the issues you mentioned
