### ISSUE TITLE
Refactor class component to functional component with react hooks

### ISSUE THREAD

**Issue by abhijithvijayan** [abhijithvijayan/abhijithvijayan.in#32]
The navbar is adjusted on scroll and hidden after a scroll threshold using state updates.

This is presently done using Class Components.

I have worked(but failed) on refactoring this to use hooks(no external library) but ended in inifinite component state update.

Refactor this component to use hooks(useState, useEffect ,...)

Please comment here first and then start working on this issue.

**Comment by quaj** [comment]
check #33

**Comment by ayoola-solomon** [comment]
@abhijithvijayan you meant you want to change this [file](https://github.com/abhijithvijayan/abhijithvijayan.in/blob/master/components/Header/Header.js) to a functional component ?
